### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Review by lassoan — APPROVED** [review]

**Review by lassoan — APPROVED** [review]

**Review by lassoan — APPROVED** [review]
Thank you, looks good.

**Comment by jcfr** [comment]
Please, could this be approved & merged :pray: 

Despite of @lassoan written approval, I am not able to move forward with the integration.

**Review by lassoan — APPROVED** [review]

**Review by lassoan — APPROVED** [review]

**Comment by lassoan** [comment]
@fedesemeraro you need to approve and merge this pull request.

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @fedesemeraro with @lassoan in cc:

```
Subject: Help to merge https://github.com/fedesemeraro/SlicerTomoSAM pull requests

Hi Federico,

When you have a chance, we would appreciate your help to merge the following pull requests:

  ENH: Update extension metadata
  https://github.com/fedesemeraro/SlicerTomoSAM/pull/18

  Updated README to add version specifications of 3D Slicer
  https://github.com/fedesemeraro/SlicerTomoSAM/pull/10

Changes are trivial as they include an update to the documentation and extension metadata.

Thanks
J-Christophe
```

**Comment by jcfr** [comment]
Follow-up email sent on June 18th 2024 to @fedesemeraro with @lassoan in cc:

```
Hi Federico, 

Let us know if you need anything to move forward with the integration of the referenced pull requests.

Thanks
J-Christophe
```

**Review by fedesemeraro — APPROVED** [review]

**Comment by fedesemeraro** [comment]
Apologies for the long delay, I have been out for the past 4 weeks. Merging now, thank you for your fix

**Pull request merged**
